name: .NET Unit Tests

on:
  push:
    branches: [ main, develop, infra/runner-toevoegen ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore

      - name: Build (Core + Tests)
        run: dotnet build --configuration Release --no-restore

      - name: Test (NUnit – TestCore)
        run: dotnet test ./TestCore/TestCore.csproj -c Release --no-build \
             --logger "trx;LogFileName=tests.trx" \
             --results-directory ./TestResults

      - name: Upload test artefacts
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: TestResults/*.trx
